version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: ubuntu
  BeforeInstall:
    - location: scripts/cleanup.sh
      runas: ubuntu
  AfterInstall:
    - location: scripts/install_dependencies.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      runas: ubuntu
