version: '3.8'

services:
  # ================== API Gateway ==================
  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - devices-service
      - project-service
      - point-service
      - export-service
      - mqtt-service
      - notification-service
    environment:
      - PORT=5000
      - API_AUTH_URL=http://auth-service:5002
      - API_DEVICES_URL=http://devices-service:5003
      - API_PROJECTS_URL=http://project-service:5004
      - API_POINTS_URL=http://point-service:5005
      - API_EXPORT_URL=http://export-service:5006
      - API_MQTT_URL=http://mqtt-service:5007
      - API_NOTIFICATIONS_URL=http://notification-service:5008

  # ================== Microservices ==================
  auth-service:
    build: ./src/services/auth-service
    ports:
      - "5002:5002"

  devices-service:
    build: ./src/services/device-service
    ports:
      - "5003:5003"

  project-service:
    build: ./src/services/project-service
    ports:
      - "5004:5004"

  point-service:
    build: ./src/services/point-service
    ports:
      - "5005:5005"

  export-service:
    build: ./src/services/export-service
    ports:
      - "5006:5006"

  mqtt-service:
    build: ./src/services/mqtt-service
    ports:
      - "5007:5007"

  notification-service:
    build: ./src/services/notification-service
    ports:
      - "5008:5008"
