name: Deploy Dockerized App to EC2 via CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Create CodeDeploy deployment from GitHub
        run: |
          aws deploy create-deployment \
            --application-name Geonex \
            --deployment-group-name GeonexGroup \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
            --deployment-config-name CodeDeployDefault.EC2OneAtATime \
            --description "Deployment from GitHub Actions - ${{ github.sha }}"